import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'core/observability/app_logger.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  AppLogger.init();
  // Initialise Firebase — required by firebase_messaging for push.
  // The options are read from `firebase_options.dart` (generated by
  // `flutterfire configure`). For now we wrap in a try/catch so the
  // app still boots if Firebase isn't configured yet.
  try {
    await Firebase.initializeApp();
  } catch (e, s) {
    AppLogger.warning('Firebase init failed (push will be disabled)', e, s);
  }
  runApp(
    const ProviderScope(
      child: KhongdichApp(),
    ),
  );
}
